### ISSUE TITLE
Works with Leaflet 1.6.0

### ISSUE THREAD

**Issue by jcanchor** [Raruto/leaflet-gesture-handling#1]
I tested your leaflet-gesture-handling v1.2.2 with Leaflet v1.6.0 and it works! I could not get elmarqluis v1.1.8 to work at all with any version of Leaflet.

Thank you for providing this plugin!

**Comment by Raruto** [comment]
Thanks Jim,
if this may interest you, this plugin is also already included by default in the [leaflet-ui](https://github.com/Raruto/leaflet-ui) project (check it out if you're just starting to build your own map).

_Have a nice Year,
Raruto_

**Comment by jcanchor** [comment]
Thank you for suggesting the [leaflet-uri](https://github.com/Raruto/leaflet-ui) project. It gives users more options and functionality than I thought was available for OpenStreetMap.

Your UI makes everything very easy to implement and customize.
