### ISSUE TITLE
Question about pull request

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-gesture-handling#14]
Hi Raruto,

I'm using your repository since last year. Now you seem to be developing it further.
I have made two changes:

- There is a [bug in Leaflet 1.7 .1](https://github.com/Leaflet/Leaflet/issues/7255) with Safari, I deal it with https://github.com/hupe13/extensions-leaflet-map-github/blob/bb532555d4fbf0687e964f8847a393d9fa75e5f3/leaflet-plugins/leaflet-gesture-handling-1.4.1/leaflet-gesture-handling-leafext.js#L105-L113 . The bug is solved in Leaflet 1.8.
- To make [L.control.layers](https://leafletjs.com/examples/layers-control/) and [Leaflet.Control.Opacity](https://github.com/dayjournal/Leaflet.Control.Opacity) work together with gesture handling, I have made the following changes: https://github.com/hupe13/extensions-leaflet-map-github/blob/bb532555d4fbf0687e964f8847a393d9fa75e5f3/leaflet-plugins/leaflet-gesture-handling-1.4.1/leaflet-gesture-handling-leafext.js#L205-L217 . Without these changes it is difficult to operate the control fields on touch devices.

May I make a pull request?

Thank you very much.

**Comment by Raruto** [comment]
Sure, but send two of those so we can discuss them separately.

_Raruto_
