### ISSUE TITLE
Desktop and mobile behavior

### ISSUE THREAD

**Issue by hupe13** [Raruto/leaflet-gesture-handling#19]
It's not a problem, it's a question.
I have tested leafet-gesture-handling with map options `dragging` and `scrollWheelZoom` by setting this to true and false.
I have observed that scrollWheelZoom must be true on the desktop, regardless of dragging.
On a mobile (tested with Android) either scrollWheelZoom or dragging must be true.
Is that the expected behavior?

Thank you very much.

**Comment by Raruto** [comment]
Hi hupe,
yes, it is the consequence of this pull: https://github.com/Raruto/leaflet-gesture-handling/pull/18 (do you think I missed something?)

_Raruto_

**Comment by hupe13** [comment]
No. You haven't missed anything. I just want to have it confirmed that it is so correct. 
My query to enable GestureHandling until now was:

```js
if ( map.dragging.enabled() || map.scrollWheelZoom.enabled() ) {
    map.gestureHandling.enable();
}
```
Apparently I no longer need this query. But I have to write this in the helping page.

Thank you very much.

**Comment by hupe13** [comment]
I need the query, because I add leaflet-gesture-handling to an existing map.
So the query would be:

```js
if ( ( (map.dragging.enabled() || map.scrollWheelZoom.enabled()) && L.Browser.mobile ) || ( map.scrollWheelZoom.enabled() && !L.Browser.mobile )) {
    map.gestureHandling.enable();
}
```

**Comment by Raruto** [comment]
@hupe13 in my opinion it works the same even without those conditions, but an extra check doesn't hurt anyone anyway 😄

_Raruto_

**Comment by hupe13** [comment]
I need these checks because of my configuration. It doesn't work without these.
I have tested, researched and learned a lot about `scrollWheelZoom` and `dragging` on desktop and mobile. On the desktop `scrollWheelZoom: true `and `dragging: false` works as expected, but on a mobile not. There I can move the map anyway, which should not be. But this has nothing to do with leaflet-gesture-handling.
