### ISSUE TITLE
Unable to drag up or down the page

### ISSUE THREAD

**Issue by endlessuniverse** [Raruto/leaflet-gesture-handling#5]
I tried this plugin and also the other called leaflet-ui.
I'm unable to drag up or down the page like in this demo: https://elmarquis.github.io/Leaflet.GestureHandling/examples/
Thank you for this fork!
Edit: Dragging works once, but not later.

**Comment by Raruto** [comment]
Hi endlessuniverse,

maybe you are using leaflet v1.7.1, I've updated the main [example](https://raruto.github.io/leaflet-gesture-handling/examples/leaflet-gesture-handling.html) to make it work latest release of this library (**1.3.1**).

_Have a nice day,
Raruto_

**Comment by endlessuniverse** [comment]
Thanks a lot!!!

**Comment by endlessuniverse** [comment]
That didn't fix the issue. Please try this example https://elmarquis.github.io/Leaflet.GestureHandling/examples/ with your script.

**Comment by Raruto** [comment]
That example has some HTML validation errors (ref. `<ul>` and `<body>` tags)

Here it is the same [example](https://jsfiddle.net/nywbLrpg/) where I changed these libraries:

```html
<!-- Leaflet Gesture Handling -->
<link rel="stylesheet" href="https://unpkg.com/@raruto/leaflet-gesture-handling@1.3.1/dist/leaflet-gesture-handling.min.css" type="text/css">
<script src="https://unpkg.com/@raruto/leaflet-gesture-handling@1.3.1/dist/leaflet-gesture-handling.min.js"></script>
```

**Comment by endlessuniverse** [comment]
Still no luck. I can drag up/down at first but when I release and try to drag again, it's blocked.
This demo https://elmarquis.github.io/Leaflet.GestureHandling/examples/ with the original script works as expected.

**Comment by Raruto** [comment]
I didn't get it right then, does it work now with version **1.3.2**? https://jsfiddle.net/17g6o543/

**Comment by endlessuniverse** [comment]
It works great! Thank you very much!
