### ISSUE TITLE
Zooming in or out over tooltip will activate zoom in browser

### ISSUE THREAD

**Issue by MikaelPorttila** [Raruto/leaflet-gesture-handling#6]
Bug:
If the user press ctrl + scroll to zoom out but the mouse is over a leaflet tooltip, the whole browser will zoom instead.

Two solutions:
- Zoom events on tooltips should be forwarded to the geasture handler, this is not an issue with legends, maybe this has been handled already for other types of controls?
- Make zoom command key a config which can be change to other keys (shift, alt) 

*Update*
Only the geoJSON feature tooltips have this issue, regular L.Tooltips works fine.

*Update 2*
Created a fiddle example, click in the orange area so the popup gets displayed and then try to ctrl + scroll over the tooltip: 
https://jsfiddle.net/Lpgsdajb/1/

**Comment by Raruto** [comment]
Hi Mikael,
maybe you were referring to [popups](https://leafletjs.com/reference-1.7.1.html#popup) ([tooltips](https://leafletjs.com/reference-1.7.1.html#tooltip) are another thing) 

Anyway, it should be fixed from version **1.3.3** (ref. https://github.com/Raruto/leaflet-gesture-handling/commit/634715f43af941c559fed3981d0246e597989b67).

_Have a nice day,
Raruto_
